# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

#Rails.application.config.assets.precompile += %w( animate.css.scss )
#Rails.application.config.assets.precompile += %w( bootstrap.css.map.scss )
#Rails.application.config.assets.precompile += %w( colors/color1.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color2.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color3.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color4.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color5.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color6.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color7.css.scss )
#Rails.application.config.assets.precompile += %w( colors/color8.css.scss )
#Rails.application.config.assets.precompile += %w( flexslider.css.scss )
#Rails.application.config.assets.precompile += %w( font-awesome.css.scss )
#Rails.application.config.assets.precompile += %w( icomoon.css.scss )
#Rails.application.config.assets.precompile += %w( magnific-popup.css.scss )
#Rails.application.config.assets.precompile += %w( owl.carousel.css.scss )
#Rails.application.config.assets.precompile += %w( responsive.css.scss )
#Rails.application.config.assets.precompile += %w( revolution-slider.css.scss )
#Rails.application.config.assets.precompile += %w( shortcodes.css.scss )
#Rails.application.config.assets.precompile += %w( style.css.scss )

# Rails.application.config.assets.precompile += %w( bootstrap.min )
# Rails.application.config.assets.precompile += %w( jquery.easing )
# Rails.application.config.assets.precompile += %w( imagesloaded.min )
# Rails.application.config.assets.precompile += %w( jquery.isotope.min )
# Rails.application.config.assets.precompile += %w( owl.carousel )
# Rails.application.config.assets.precompile += %w( jquery.mb.YTPlayer )
# Rails.application.config.assets.precompile += %w( jquery-waypoints )
# Rails.application.config.assets.precompile += %w( jquery.flexslider-min )
# Rails.application.config.assets.precompile += %w( jquery.cookie )
# Rails.application.config.assets.precompile += %w( jquery.fitvids )
# Rails.application.config.assets.precompile += %w( jquery-validate )
# Rails.application.config.assets.precompile += %w( jquery.magnific-popup.min )
# Rails.application.config.assets.precompile += %w( parallax )
# Rails.application.config.assets.precompile += %w( jquery.countdown )
# Rails.application.config.assets.precompile += %w( switcher )
# Rails.application.config.assets.precompile += %w( jquery.sticky )
# Rails.application.config.assets.precompile += %w( smoothscroll )
# Rails.application.config.assets.precompile += %w( main )
# Rails.application.config.assets.precompile += %w( action_cable )
# Rails.application.config.assets.precompile += %w( cable )
# Rails.application.config.assets.precompile += %w( gmap3.min )
# Rails.application.config.assets.precompile += %w( html5shiv )
# Rails.application.config.assets.precompile += %w( jquery-countTo )
# Rails.application.config.assets.precompile += %w( jquery.easypiechart.min )
# Rails.application.config.assets.precompile += %w( jquery.gomap-1.3.2.min )
# Rails.application.config.assets.precompile += %w( jquery.themepunch.revolution.min )
# Rails.application.config.assets.precompile += %w( jquery.themepunch.tools.min )
# Rails.application.config.assets.precompile += %w( jquery.tweet.min )
# Rails.application.config.assets.precompile += %w( respond.min )
# Rails.application.config.assets.precompile += %w( slider )

# Rails.application.config.assets.precompile += %w( js/jquery.min.js )
# Rails.application.config.assets.precompile += %w( js/popper.js )
# Rails.application.config.assets.precompile += %w( jquery-slimscroll/jquery.slimscroll.js )
# Rails.application.config.assets.precompile += %w( js/bootstrap.min.js )
# Rails.application.config.assets.precompile += %w( js/jquery.blockui.min.js )
# Rails.application.config.assets.precompile += %w( js/app.js )
# Rails.application.config.assets.precompile += %w( js/layout.js )
# Rails.application.config.assets.precompile += %w( js/theme-color.js )
# Rails.application.config.assets.precompile += %w( js/material.min.js )
# Rails.application.config.assets.precompile += %w( getmdl-select.js )
# Rails.application.config.assets.precompile += %w( plugins/jquery-ui/jquery-ui.min.js )
# Rails.application.config.assets.precompile += %w( plugins/moment/moment.min.js )
# Rails.application.config.assets.precompile += %w( plugins/fullcalendar/fullcalendar.js )
# Rails.application.config.assets.precompile += %w( calendar.min.js )
# Rails.application.config.assets.precompile += %w( plugins/datatables/jquery.dataTables.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/dataTables.buttons.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/buttons.flash.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/jszip.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/pdfmake.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/vfs_fonts.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/buttons.html5.min.js)
# Rails.application.config.assets.precompile += %w( plugins/datatables/export/buttons.print.min.js)
# Rails.application.config.assets.precompile += %w( js/pages/table/table_data.js)
# Rails.application.config.assets.precompile += %w( plugins/material-datetimepicker/moment-with-locales.min.js)
# Rails.application.config.assets.precompile += %w( plugins/material-datetimepicker/bootstrap-material-datetimepicker.js)
# Rails.application.config.assets.precompile += %w( plugins/material-datetimepicker/datetimepicker.js)
# Rails.application.config.assets.precompile += %w( icons-lte-ie7.js )
# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )